CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY,
    content TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    prev INTEGER REFERENCES messages(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS refs (
    ref TEXT PRIMARY KEY,
    tail INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE
);
